// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbDXumA5bGat7wKeolDd9OgA1iO61Qua8',
    appId: '1:420452724549:android:b2c881e2fabace8bc6182c',
    messagingSenderId: '420452724549',
    projectId: 'event-mate-fyp-bsse',
    storageBucket: 'event-mate-fyp-bsse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTQ3TYOBwWvBGoCEVJM-5pm2vMM2iYvuk',
    appId: '1:420452724549:ios:8fc21f80c9378f88c6182c',
    messagingSenderId: '420452724549',
    projectId: 'event-mate-fyp-bsse',
    storageBucket: 'event-mate-fyp-bsse.appspot.com',
    androidClientId: '420452724549-c7h73t6c0bokqimhun2qo8ck2ir9gbu0.apps.googleusercontent.com',
    iosClientId: '420452724549-pae9v1ishiah9q8hqb2g2ppsntkb06hs.apps.googleusercontent.com',
    iosBundleId: 'com.fyp.eventMate',
  );

}